Repository gyuri2020/codethestudent, pull requests merged in 2021-11, with the labels that each got.

#2 Init Naver Shopping Search API
  package-lock.json
  package.json
  src/api.js
  src/components/Content.vue
Labels: enhancement, front-end, API

#18 Add favicon
  public/index.html
  public/shirt.ico
Labels: enhancement, front-end

#8 Documentation 추가
  README.md
Labels: documentation, github
